### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by devildeveloper** [markotom/restify-url-semver#3]
Hi, i have it error when launch ... its works
![captura de pantalla 2016-05-01 a las 0 37 40](https://cloud.githubusercontent.com/assets/2333365/14940264/212ff254-0f35-11e6-9009-56b1b870ccc8.png)
![captura de pantalla 2016-05-01 a las 0 38 07](https://cloud.githubusercontent.com/assets/2333365/14940265/29e0cc7a-0f35-11e6-9e89-89fae62f7a4c.png)

**Comment by markotom** [comment]
Please, take a look to this issue: https://github.com/restify/node-restify/issues/897
I think is an error of Restify and node version.

But, thanks for your comment.
