### ISSUE TITLE
req.url is malformed after middleware exits

### ISSUE THREAD

**Issue by erkurita** [markotom/restify-url-semver#4]
After going through the middleware, the parameter `req.url` has a trailing slash at the beginning, breaking the RegExp routes. I've found that [this line](https://github.com/markotom/restify-url-semver/blob/8c4ff3185210a8db016b9ba996e624093e044e1f/index.js#L23) performs a replace removing the versioning, without removing one of the slashes.

**Comment by markotom** [comment]
Thanks for your comment,

I think it might be fixed with a simple regular expression. But, I don't have free time to resolve it. Can you help me with a PR? 😄

**Comment by vampirical** [comment]
Here's a PR with a fix: https://github.com/markotom/restify-url-semver/pull/8

**Comment by markotom** [comment]
Thank you @vampirical
